### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by aminta** [wizzomafizzo/MiSTer_Favorites#5]
Last version of MISTer_Favorites, Python 3.9.6

`/media/fat/Scripts# python favorites.sh
Traceback (most recent call last):
  File "/media/fat/Scripts/favorites.sh", line 1018, in <module>
    refresh_favorites()
  File "/media/fat/Scripts/favorites.sh", line 678, in refresh_favorites
    for entry in get_favorites():
  File "/media/fat/Scripts/favorites.sh", line 188, in get_favorites
    favorites.append([get_favorite_target(path), path])
  File "/media/fat/Scripts/favorites.sh", line 154, in get_favorite_target
    match = re.search(r'path="\.\./\.\./\.\./\.\.(.+)"', f.read())
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte`

**Comment by wizzomafizzo** [comment]
Hi. Can you please give the newest update a shot. I'm not sure why this would happen unless you're willing to upload a copy of all your mgl files for me to look at. But in this new version I have handled this error and made it skip the favorite rather than crash the whole program. Let me know how it goes, this might be enough

**Comment by aminta** [comment]
> Hi. Can you please give the newest update a shot. I'm not sure why this would happen unless you're willing to upload a copy of all your mgl files for me to look at. But in this new version I have handled this error and made it skip the favorite rather than crash the whole program. Let me know how it goes, this might be enough

Ok, new version works! Thanks!
